# Generated by Django 5.2 on 2025-04-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionrecord',
            name='action_items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptionrecord',
            name='key_phrases',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptionrecord',
            name='meeting_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptionrecord',
            name='speaker_dynamics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
